module.exports={
    devServer:{
        proxy:{
            '/ajax':{
                target:'http://m.maoyan.com',
                changeOrigin:true
            },
            'public':{
                target:'http://localhost:8080',
                changeOrigin:true
            }
        }
    }
}